version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    environment:
      PORT: "8080"
